# MOSES: DNA Coloring Algorithm

Contributors: Dr. Jason Kahn (Brookhaven), Sarah Hong (Columbia)

This notebook shows the final workflow for how to create a lattice structure and paint it.

In [1]:
# Load this cell so that changes made in other files will be automatically reflected
%load_ext autoreload
%autoreload 2

In [2]:
# Run this cell to load all imports
import sys
sys.path.append('../')

import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

from app.design.Designer import RunDesigner
from app.visualize.Visualizer import RunVisualizer
from algorithm.lattice.Lattice import Lattice
from algorithm.painting.Painter2 import Painter
from algorithm.symmetry.Rotation import NpRotationDict
from algorithm.painting.BindingFlexibility import BindingFlexibility

## Create the lattice
Run the below cell to open a GUI which allows you to quickly create arbitrary lattice structures. These lattices are encoded as numpy arrays and are saved to a (renamable) file called `lattice.npy` in the `notebooks/data` subdirectory. You can also use this feature to save and reload arbitrary lattice designs you've previously created.

In [3]:
%gui qt

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()
    
    designer = RunDesigner(app)
    input_lattice = designer.run()
    
    if input_lattice is not None:
        print('Lattice received.')
        # rename this to whatever you want to call your lattice
        np.save("data/lattice.npy", input_lattice) 
    else:
        print("No lattice received.")

No lattice received.

## Running the algorithm

### Load lattice from file
We can load in the lattice we created with `np.load(filename.npy)`. Since the lattice is just a numpy array, you can also create your own arbitrary lattices without the designer by creating arbitrary numpy arrays yourself.

Some examples to run:
- `double_oreo.npy`
- `perovskite.npy`

### Painting algorithm
All you need to do to run the algorithm is to create a Lattice instance, `compute_symmetries()`, create a Painter instance, and `paint_lattice()`.

The example workflow is detailed below.

In [7]:
np.save("data/mini_helix.npy", input_lattice)

In [32]:
# input_lattice = np.load('data/double_oreo.npy', allow_pickle=True)

# An example lattice structure you can load in
input_lattice = np.load('data/helix.npy')

# Initialize the data structures and compute all symmetries
lattice = Lattice(input_lattice)
lattice.compute_symmetries()

# Paint the lattice
# painter = Painter(lattice, verbose=True) # Set verbose=True to print debug
# # painter.str_paint_lattice()
# # painter.comp_paint_lattice()
# painter.paint_lattice()

In [43]:
%gui qt

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()
    
    visualizeWindow = RunVisualizer(lattice=lattice, voxels=lattice.voxels, app=app) # insert bf_lattice here if you want
    # visualizeWindow = RunVisualizer(lattice=lattice, voxels=str_voxels, app=app) # insert bf_lattice here if you want

In [46]:
voxel_7 = lattice.get_voxel(7)
symdict_7 = lattice.symmetry_df.symdict(4)

for partner_id, symlist in symdict_7.items():
    print(f"(4, {partner_id}): {symlist}")

(4, 4): ['translation', '180° X-axis + 270° Z-axis', '180° Y-axis + 90° Z-axis']
(4, 14): ['180° Y-axis', '270° Z-axis', '180° Z-axis + 180° X-axis']
(4, 26): ['180° Z-axis', '180° X-axis + 90° Z-axis', '180° Y-axis + 180° X-axis', '180° Y-axis + 270° Z-axis']
(4, 34): ['180° X-axis', '90° Z-axis', '180° Z-axis + 180° Y-axis']

In [54]:
print(f"MinDesign shape: {lattice.MinDesign.shape}")
print(f"Full surroundings shape: {lattice.Surroundings.FullSurroundings.shape}")
print(f"Tile repeats: {lattice.Surroundings.tile_repeats}")

MinDesign shape: (4, 3, 3)
Full surroundings shape: (12, 15, 15)
Tile repeats: [3, 5, 5]

In [7]:
lattice.MinDesign

array([[[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0]]])

In [15]:
voxel_7 = lattice.get_voxel(7)
voxel_7_surr = lattice.Surroundings.voxel_surroundings(voxel_7, verbose=True)

print("\nSurroundings for voxel 7")
voxel_7_surr

Halfway points for each direction: ((4, 6, 6))
Slicing full_surr @ ((4, 8, 7))

Surroundings for voxel 7

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0]],

       [[0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [16]:
print("Voxel 5 surroundings\n")

voxel_5 = lattice.get_voxel(5)
voxel_5_surr = lattice.Surroundings.voxel_surroundings(voxel_5)

voxel_5_surr

Voxel 5 surroundings

array([[[0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 1, 0, 0, 1],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0]]])

In [23]:
# test out whether the double rotation itself is wrong or not

rot = surr_rotater.all_rotations['180° X-axis']
arr = np.array([[[1, 2],
                 [3, 4]],
                [[5, 6],
                 [7, 8]]])
print(f"Original arr\n{arr}")
rot_arr = rot(arr)
print(f"180x rotation\n{rot_arr}")

rot2 = surr_rotater.all_rotations['180° X-axis + 90° Z-axis']
rot_arr2 = rot2(arr)
print(f"180x + 90z rotation\n{rot_arr2}")

Original arr
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
180x rotation
[[[7 8]
  [5 6]]

 [[3 4]
  [1 2]]]
180x + 90z rotation
[[[8 6]
  [7 5]]

 [[4 2]
  [3 1]]]

In [17]:
surr_rotater = NpRotationDict()

# rot = surr_rotater.all_rotations['180° X-axis + 270° Z-axis']
rot = surr_rotater.all_rotations['180° X-axis + 90° Z-axis']

rot_surr_7 = rot(voxel_7_surr)
rot_surr_7

array([[[0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0]],

       [[0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0]]])

In [18]:
print(f"Rotated voxel 7 surr = voxel 5 surr?{np.array_equal(rot_surr_7, voxel_5_surr)}")

Rotated voxel 7 surr = voxel 5 surr?False

In [25]:
s_voxels = painter.mesovoxel.structural_voxels
c_voxels = painter.mesovoxel.complementary_voxels

min_voxels = s_voxels | c_voxels
print(f"min voxel set: {min_voxels}")

min_voxels = [lattice.get_voxel(mv) for mv in min_voxels]
str_voxels = [lattice.get_voxel(sv) for sv in s_voxels]

min voxel set: {0, 1, 2, 4, 5, 8, 27, 28, 29}

## Optional: Binding Flexibility
In this section, we introduce an optional "binding flexibility" parameter, which modifies the final painting result to be stricter or looser. This is motivated by the observation that the geometry / symmetries of specific structures may perform better under different constraints, and we offer the user the option to make it more/less strict.

### Background
**Binding flexibility 1:** Reduces specificity (less colors)
- BF 1 turns all bonds to voxels in the same automorphism equivalence class are repainted to be the same color. 
- In other words, we repaint all bonds between all voxels with some symmetry between them to be the same color.

**Binding flexibility 2:** No change
- BF 2 is the default result from the Painter.paint() algorithm. It generally leads to the best results, so most systems are painted with this.

**Binding flexibility 3:** Adds specificity (more colors)
- Introducing a maximum cutoff ratio (= structural bonds / total bonds) per voxel.
- For all voxels in the lattice with a cutoff ratio higher than the maximum, we repaint a NEW color ontop of a structural bond on that voxel to lower the ratio to satisfy the constraint.
- This ratio is motivated by the observation that having more structural bonds on the same voxel makes it more likely to erroneously bind in ways we don't want.

### Usage
To repaint the lattice with a specific binding flexibility, create a new `BindingFlexibility` instance specified with a given (painted) lattice object. Then run either `binding_flexibility1()` or `binding_flexibility3()` and assign it to a new variable to create a NEW lattice instance which can be visualized in the app. An example usage can be run below.

In [7]:
bf = BindingFlexibility(lattice)

bf1_lattice = bf.binding_flexibility_1()
bf3_lattice = bf.binding_flexibility_3(max_cutoff_ratio=1/6)

## Visualize the painted lattice

Run the below cell to view the painted lattice as a result from the algorithm.

To view a specific binding flexibility in the app, just supply the given binding flexibility lattice as the argument to `RunVisualizer`.

In [7]:
%gui qt

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()
    
    visualizeWindow = RunVisualizer(lattice=lattice2, voxels=lattice2.voxels.values(), app=app) # insert bf_lattice here if you want
    # visualizeWindow = RunVisualizer(lattice=lattice, voxels=str_voxels, app=app) # insert bf_lattice here if you want

In [18]:
for voxel in lattice.voxels:
    print(f"Voxel{voxel.id} is {voxel.type}")

Voxel0 is structural
Voxel1 is complementary
Voxel2 is complementary
Voxel3 is structural
Voxel4 is structural
Voxel5 is complementary
Voxel6 is complementary
Voxel7 is structural
Voxel8 is complementary
Voxel9 is structural
Voxel10 is structural
Voxel11 is complementary
Voxel12 is complementary
Voxel13 is structural
Voxel14 is structural
Voxel15 is complementary

## Minimal origami set

You can run `lattice.final_df()` to get an interpretable, final dataframe which contains all voxel/bond information.

In [ ]:
lattice.unique_origami()

In [17]:
final_df = lattice.final_df()
final_df

  Voxel                      Bond Colors
     ID Material Coordinates          +x -x +y -y +z -z
0     0        1   (0, 1, 1)           1  1  1  1  1  1
1     1        0   (1, 1, 1)          -1 -1  2  2  2  2
2     2        0   (0, 0, 1)           2  2 -1 -1  2  2
3     3        2   (1, 0, 1)          -2 -2 -2 -2  3  3
4     4        0   (0, 1, 0)           2  2  2  2 -1 -1
5     5        2   (1, 1, 0)          -2 -2  3  3 -2 -2
6     6        2   (0, 0, 0)           3  3 -2 -2 -2 -2
7     7        3   (1, 0, 0)          -3 -3 -3 -3 -3 -3

In [7]:
from scipy.spatial.transform import Rotation
import numpy as np

# new type of voxel surroundings - as dictionary
surr = {
    (1, 0, 0): 1,
    (0, 1, 0): 0,
    (0, 0, 1): 1,
    (1, 1, 1): 0
}

rotation = Rotation.from_euler('z', 360, degrees=True) # get this from the dict later

# convert coords and materials to their own np.arrays
surr_keys = np.array(list(surr.keys()))
surr_values = list(surr.values())

rot_surr_keys = rotation.apply(surr_keys)
rot_surr_keys = np.round(rot_surr_keys).astype(int)
rot_surr = {tuple(key): value for key, value in zip(rot_surr_keys, surr_values)}

if set(surr.keys()) == set(rot_surr.keys()):
    all_match = all(surr[key] == rot_surr[key] for key in surr.keys())

else:
    all_match = False

print(f"all materials match after rotation?: {all_match}")

rot_surr

all materials match after rotation?: True

{(np.int64(1), np.int64(0), np.int64(0)): 1,
 (np.int64(0), np.int64(1), np.int64(0)): 0,
 (np.int64(0), np.int64(0), np.int64(1)): 1,
 (np.int64(1), np.int64(1), np.int64(1)): 0}

In [8]:
# Define the maximum dimension
max_dim = 3  # Example value

# Generate 1D array of coordinates for each axis
coords_range = np.linspace(-max_dim, max_dim, num=2*max_dim + 1)

# Generate the 3D grid of coordinates
x, y, z = np.meshgrid(coords_range, coords_range, coords_range, indexing='ij')

# Flatten the grids and combine them into a list of 3D coordinates
coords = np.array([x.flatten(), y.flatten(), z.flatten()]).T

print("All possible coordinates within the cube:")
print(coords)

All possible coordinates within the cube:
[[-3. -3. -3.]
 [-3. -3. -2.]
 [-3. -3. -1.]
 ...
 [ 3.  3.  1.]
 [ 3.  3.  2.]
 [ 3.  3.  3.]]

In [5]:
from algorithm.lattice.Lattice2 import Lattice2
from algorithm.symmetry.Surroundings2 import Surroundings2

# An example lattice structure you can load in
input_lattice = np.load('data/helix.npy')

# Initialize the data structures and compute all symmetries
lattice2 = Lattice2(input_lattice)
lattice2.compute_symmetries()

lattice2.symmetry_df.symmetry_df

,translation,90° X-axis,180° X-axis,270° X-axis,90° Y-axis,180° Y-axis,270° Y-axis,90° Z-axis,180° Z-axis,270° Z-axis,...,90° X-axis + 90° Z-axis,90° Y-axis + 180° X-axis,90° Y-axis + 180° Z-axis,90° Y-axis + 270° X-axis,90° Y-axis + 270° Z-axis,90° Y-axis + 90° X-axis,90° Y-axis + 90° Z-axis,90° Z-axis + 180° X-axis,90° Z-axis + 270° X-axis,90° Z-axis + 270° Y-axis
"(4, 25)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(2, 8)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(7, 31)",False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(13, 34)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(15, 30)",False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"(14, 26)",False,False,True,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
"(9, 33)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(11, 20)",False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(27, 34)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(5, 28)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
painter2 = Painter(lattice2, verbose=True) # Set verbose=True to print debug
# painter.str_paint_lattice()
# painter.comp_paint_lattice()
painter2.paint_lattice()

===== STARTING STR_PAINT_LATTICE =====

--- PAINT S_BOND (1) ---
voxel_0 ((1, 0, 0)) <---> voxel_1 ((-1, 0, 0))
self-sym paint(voxel_0)
    map_paint(parent_0 --> child_0, sym=translation, with_negation=False)
    map_paint(parent_0 --> child_0, sym=180° Y-axis + 270° Z-axis, with_negation=False)
    map_paint(parent_0 --> child_0, sym=270° Z-axis + 180° X-axis, with_negation=False)
self-sym paint(voxel_1)
    map_paint(parent_1 --> child_1, sym=translation, with_negation=False)

--- PAINT S_BOND (2) ---
voxel_0 ((-1, 0, 0)) <---> voxel_2 ((1, 0, 0))
self-sym paint(voxel_0)
    map_paint(parent_0 --> child_0, sym=translation, with_negation=False)
    map_paint(parent_0 --> child_0, sym=180° Y-axis + 270° Z-axis, with_negation=False)
    map_paint(parent_0 --> child_0, sym=270° Z-axis + 180° X-axis, with_negation=False)
self-sym paint(voxel_2)
    map_paint(parent_2 --> child_2, sym=translation, with_negation=False)

--- PAINT S_BOND (3) ---
voxel_1 ((1, 0, 0)) <---> voxel_2 ((-1, 0, 0))
self-sym paint(voxel_1)
    map_paint(parent_1 --> child_1, sym=translation, with_negation=False)
self-sym paint(voxel_2)
    map_paint(parent_2 --> child_2, sym=translation, with_negation=False)

--- PAINT S_BOND (4) ---
voxel_1 ((0, -1, 0)) <---> voxel_4 ((0, 1, 0))
self-sym paint(voxel_1)
    map_paint(parent_1 --> child_1, sym=translation, with_negation=False)
self-sym paint(voxel_4)
    map_paint(parent_4 --> child_4, sym=translation, with_negation=False)
    map_paint(parent_4 --> child_4, sym=180° Y-axis + 270° Z-axis, with_negation=False)
    map_paint(parent_4 --> child_4, sym=270° Z-axis + 180° X-axis, with_negation=False)

--- PAINT S_BOND (5) ---
voxel_2 ((0, 1, 0)) <---> voxel_8 ((0, -1, 0))
self-sym paint(voxel_2)
    map_paint(parent_2 --> child_2, sym=translation, with_negation=False)
self-sym paint(voxel_8)
    map_paint(parent_8 --> child_8, sym=translation, with_negation=False)
    map_paint(parent_8 --> child_8, sym=180° Y-axis + 270° Z-axis, with_negation=False)
    map_paint(parent_8 --> child_8, sym=270° Z-axis + 180° X-axis, with_negation=False)

--- PAINT S_BOND (6) ---
voxel_2 ((0, -1, 0)) <---> voxel_5 ((0, 1, 0))
self-sym paint(voxel_2)
    map_paint(parent_2 --> child_2, sym=translation, with_negation=False)
self-sym paint(voxel_5)
    map_paint(parent_5 --> child_5, sym=translation, with_negation=False)

--- PAINT S_BOND (7) ---
voxel_4 ((1, 0, 0)) <---> voxel_5 ((-1, 0, 0))
self-sym paint(voxel_4)
    map_paint(parent_4 --> child_4, sym=translation, with_negation=False)
    map_paint(parent_4 --> child_4, sym=180° Y-axis + 270° Z-axis, with_negation=False)
    map_paint(parent_4 --> child_4, sym=270° Z-axis + 180° X-axis, with_negation=False)
self-sym paint(voxel_5)
    map_paint(parent_5 --> child_5, sym=translation, with_negation=False)

--- PAINT S_BOND (8) ---
voxel_5 ((0, -1, 0)) <---> voxel_8 ((0, 1, 0))
self-sym paint(voxel_5)
    map_paint(parent_5 --> child_5, sym=translation, with_negation=False)
self-sym paint(voxel_8)
    map_paint(parent_8 --> child_8, sym=translation, with_negation=False)
    map_paint(parent_8 --> child_8, sym=180° Y-axis + 270° Z-axis, with_negation=False)
    map_paint(parent_8 --> child_8, sym=270° Z-axis + 180° X-axis, with_negation=False)

===== STARTING COMP_PAINT_LATTICE =====


LOOP 0: Between voxel1 (0)'s bond +z and voxel2 (27)'s bond -z
---
MESOPARENT: Only found str_mp 0 and it IS voxel1. Flipping complementarity when mapping.
    map_paint(parent_0 --> child_27, sym=180° X-axis, with_negation=True)

--- PAINT C_BOND (9) ---
voxel_0 ((0, 0, 1)) <---> voxel_27 ((0, 0, -1))

self-sym paint(voxel_0)
    map_paint(parent_0 --> child_0, sym=translation, with_negation=False)
    map_paint(parent_0 --> child_0, sym=180° Y-axis + 270° Z-axis, with_negation=False)
    map_paint(parent_0 --> child_0, sym=270° Z-axis + 180° X-axis, with_negation=False)
self-sym paint(voxel_27)
    map_paint(parent_27 --> child_27, sym=translation, with_negation=False)
    map_paint(parent_27 --> child_27, sym=180° Y-axis + 90° Z-axis, with_negation=False)
    map_paint(parent_27 --> child_27, sym=90° Z-axis + 180° X-axis, with_negation=False)
mapping child voxel_27 back onto parent voxel_0
    map_paint(parent_27 --> child_0, sym=180° X-axis, with_negation=True)
    map_paint(parent_27 --> child_0, sym=90° Z-axis, with_negation=True)
    map_paint(parent_27 --> child_0, sym=180° Y-axis + 180° Z-axis, with_negation=True)

LOOP 1: Between voxel1 (1)'s bond +y and voxel2 (7)'s bond -y
---
MESOPARENT: Only found str_mp 5 and it's not voxel1. (No flip comp)
    map_paint(parent_5 --> child_7, sym=180° Y-axis + 270° Z-axis, with_negation=False)

--- PAINT C_BOND (10) ---
voxel_1 ((0, 1, 0)) <---> voxel_7 ((0, -1, 0))

self-sym paint(voxel_1)
    map_paint(parent_1 --> child_1, sym=translation, with_negation=False)
self-sym paint(voxel_7)
    map_paint(parent_7 --> child_7, sym=translation, with_negation=False)
mapping child voxel_7 back onto parent voxel_5
    map_paint(parent_7 --> child_5, sym=180° Y-axis + 270° Z-axis, with_negation=False)

LOOP 2: Between voxel1 (1)'s bond +z and voxel2 (28)'s bond -z
---
MESOPARENT: Only found str_mp 1 and it IS voxel1. Flipping complementarity when mapping.
    map_paint(parent_1 --> child_28, sym=180° X-axis, with_negation=True)

--- PAINT C_BOND (11) ---
voxel_1 ((0, 0, 1)) <---> voxel_28 ((0, 0, -1))

self-sym paint(voxel_1)
    map_paint(parent_1 --> child_1, sym=translation, with_negation=False)
self-sym paint(voxel_28)
    map_paint(parent_28 --> child_28, sym=translation, with_negation=False)
mapping child voxel_28 back onto parent voxel_1
    map_paint(parent_28 --> child_1, sym=180° X-axis, with_negation=True)
    map_paint(parent_28 --> child_1, sym=180° Y-axis + 180° Z-axis, with_negation=True)

LOOP 3: Between voxel1 (1)'s bond -z and voxel2 (10)'s bond +z
---
MESOPARENT: Only found str_mp 2 and it's not voxel1. (No flip comp)
    map_paint(parent_2 --> child_10, sym=180° Y-axis, with_negation=False)

--- PAINT C_BOND (12) ---
voxel_1 ((0, 0, -1)) <---> voxel_10 ((0, 0, 1))

self-sym paint(voxel_1)
    map_paint(parent_1 --> child_1, sym=translation, with_negation=False)
self-sym paint(voxel_10)
    map_paint(parent_10 --> child_10, sym=translation, with_negation=False)
mapping child voxel_10 back onto parent voxel_2
    map_paint(parent_10 --> child_2, sym=180° Y-axis, with_negation=False)

LOOP 4: Between voxel1 (2)'s bond +z and voxel2 (29)'s bond -z
---
MESOPARENT: Only found str_mp 2 and it IS voxel1. Flipping complementarity when mapping.
    map_paint(parent_2 --> child_29, sym=180° X-axis, with_negation=True)

--- PAINT C_BOND (13) ---
voxel_2 ((0, 0, 1)) <---> voxel_29 ((0, 0, -1))

self-sym paint(voxel_2)
    map_paint(parent_2 --> child_2, sym=translation, with_negation=False)
self-sym paint(voxel_29)
    map_paint(parent_29 --> child_29, sym=translation, with_negation=False)
mapping child voxel_29 back onto parent voxel_2
    map_paint(parent_29 --> child_2, sym=180° X-axis, with_negation=True)
    map_paint(parent_29 --> child_2, sym=180° Y-axis + 180° Z-axis, with_negation=True)

LOOP 5: Between voxel1 (4)'s bond +z and voxel2 (31)'s bond -z
---
MESOPARENT: Only found str_mp 5 and it's not voxel1. (No flip comp)
    map_paint(parent_5 --> child_31, sym=90° Z-axis, with_negation=False)

--- PAINT C_BOND (14) ---
voxel_4 ((0, 0, 1)) <---> voxel_31 ((0, 0, -1))

self-sym paint(voxel_4)
    map_paint(parent_4 --> child_4, sym=translation, with_negation=False)
    map_paint(parent_4 --> child_4, sym=180° Y-axis + 270° Z-axis, with_negation=False)
    map_paint(parent_4 --> child_4, sym=270° Z-axis + 180° X-axis, with_negation=False)
self-sym paint(voxel_31)
    map_paint(parent_31 --> child_31, sym=translation, with_negation=False)
mapping child voxel_31 back onto parent voxel_5
    map_paint(parent_31 --> child_5, sym=90° Z-axis, with_negation=False)

LOOP 6: Between voxel1 (5)'s bond +z and voxel2 (32)'s bond -z
---
MESOPARENT: Only found str_mp 8 and it's not voxel1. (No flip comp)
    map_paint(parent_8 --> child_32, sym=180° X-axis, with_negation=False)

--- PAINT C_BOND (15) ---
voxel_5 ((0, 0, 1)) <---> voxel_32 ((0, 0, -1))

self-sym paint(voxel_5)
    map_paint(parent_5 --> child_5, sym=translation, with_negation=False)
self-sym paint(voxel_32)
    map_paint(parent_32 --> child_32, sym=translation, with_negation=False)
    map_paint(parent_32 --> child_32, sym=180° Y-axis + 90° Z-axis, with_negation=False)
    map_paint(parent_32 --> child_32, sym=90° Z-axis + 180° X-axis, with_negation=False)
mapping child voxel_32 back onto parent voxel_8
    map_paint(parent_32 --> child_8, sym=180° X-axis, with_negation=False)

LOOP 7: Between voxel1 (8)'s bond +z and voxel2 (35)'s bond -z
---
MESOPARENT: Only found str_mp 5 and it's not voxel1. (No flip comp)
    map_paint(parent_5 --> child_35, sym=180° X-axis, with_negation=False)

--- PAINT C_BOND (16) ---
voxel_8 ((0, 0, 1)) <---> voxel_35 ((0, 0, -1))

self-sym paint(voxel_8)
    map_paint(parent_8 --> child_8, sym=translation, with_negation=False)
    map_paint(parent_8 --> child_8, sym=180° Y-axis + 270° Z-axis, with_negation=False)
    map_paint(parent_8 --> child_8, sym=270° Z-axis + 180° X-axis, with_negation=False)
self-sym paint(voxel_35)
    map_paint(parent_35 --> child_35, sym=translation, with_negation=False)
mapping child voxel_35 back onto parent voxel_5
    map_paint(parent_35 --> child_5, sym=180° X-axis, with_negation=False)
    map_paint(parent_35 --> child_5, sym=180° Y-axis + 180° Z-axis, with_negation=False)
Mapping the mesovoxel onto the rest of the lattice...
---
skipping 0, already in mesovoxel
skipping 1, already in mesovoxel
skipping 2, already in mesovoxel
checking partner 4
checking partner 5
checking partner 0
checking partner 6
checking partner 30
checking partner 12
12 has sym and mesotype None
both str_mp 1 and comp_mp 28 exist, mapping 1 onto voxel 3
    map_paint(parent_1 --> child_3, sym=180° Y-axis + 270° Z-axis, with_negation=False)
skipping 4, already in mesovoxel
skipping 5, already in mesovoxel
checking partner 7
checking partner 8
checking partner 3
checking partner 0
checking partner 33
checking partner 15
15 has sym and mesotype None
both str_mp 2 and comp_mp 29 exist, mapping 2 onto voxel 6
    map_paint(parent_2 --> child_6, sym=180° Y-axis + 270° Z-axis, with_negation=False)
only str_mp 5 exists, mapping onto voxel 7
    map_paint(parent_5 --> child_7, sym=180° Y-axis + 270° Z-axis, with_negation=False)
skipping 8, already in mesovoxel
checking partner 10
checking partner 11
checking partner 15
checking partner 12
checking partner 0
0 has sym and mesotype structural
found partner voxel0 with type structural - setting map_variant to 27
both str_mp 0 and comp_mp 27 exist, mapping 27 onto voxel 9
    map_paint(parent_27 --> child_9, sym=180° Z-axis, with_negation=False)
checking partner 11
checking partner 9
checking partner 16
checking partner 13
checking partner 1
checking partner 19
19 has sym and mesotype None
both str_mp 2 and comp_mp 29 exist, mapping 2 onto voxel 10
    map_paint(parent_2 --> child_10, sym=180° Y-axis, with_negation=False)
checking partner 9
checking partner 10
checking partner 17
checking partner 14
checking partner 2
checking partner 20
20 has sym and mesotype None
both str_mp 1 and comp_mp 28 exist, mapping 1 onto voxel 11
    map_paint(parent_1 --> child_11, sym=180° Y-axis, with_negation=False)
checking partner 13
checking partner 14
checking partner 9
checking partner 15
checking partner 3
3 has sym and mesotype structural
found partner voxel3 with type structural - setting map_variant to 28
both str_mp 1 and comp_mp 28 exist, mapping 28 onto voxel 12
    map_paint(parent_28 --> child_12, sym=180° Y-axis + 270° Z-axis, with_negation=False)
only str_mp 5 exists, mapping onto voxel 13
    map_paint(parent_5 --> child_13, sym=180° Y-axis, with_negation=False)
only str_mp 4 exists, mapping onto voxel 14
    map_paint(parent_4 --> child_14, sym=180° Y-axis, with_negation=False)
checking partner 16
checking partner 17
checking partner 12
checking partner 9
checking partner 6
6 has sym and mesotype structural
found partner voxel6 with type structural - setting map_variant to 29
both str_mp 2 and comp_mp 29 exist, mapping 29 onto voxel 15
    map_paint(parent_29 --> child_15, sym=180° Y-axis + 270° Z-axis, with_negation=False)
only str_mp 8 exists, mapping onto voxel 16
    map_paint(parent_8 --> child_16, sym=180° Y-axis, with_negation=False)
only str_mp 5 exists, mapping onto voxel 17
    map_paint(parent_5 --> child_17, sym=270° Z-axis, with_negation=False)
checking partner 19
checking partner 20
checking partner 24
checking partner 21
checking partner 9
9 has sym and mesotype complementary
found partner voxel9 with type complementary - setting map_variant to 0
both str_mp 0 and comp_mp 27 exist, mapping 0 onto voxel 18
    map_paint(parent_0 --> child_18, sym=180° Z-axis, with_negation=False)
checking partner 20
checking partner 18
checking partner 25
checking partner 22
checking partner 10
10 has sym and mesotype structural
found partner voxel10 with type structural - setting map_variant to 29
both str_mp 2 and comp_mp 29 exist, mapping 29 onto voxel 19
    map_paint(parent_29 --> child_19, sym=180° Y-axis, with_negation=False)
checking partner 18
checking partner 19
checking partner 26
checking partner 23
checking partner 11
11 has sym and mesotype structural
found partner voxel11 with type structural - setting map_variant to 28
both str_mp 1 and comp_mp 28 exist, mapping 28 onto voxel 20
    map_paint(parent_28 --> child_20, sym=180° Y-axis, with_negation=False)
checking partner 22
checking partner 23
checking partner 18
checking partner 24
checking partner 12
checking partner 30
30 has sym and mesotype None
both str_mp 2 and comp_mp 29 exist, mapping 2 onto voxel 21
    map_paint(parent_2 --> child_21, sym=180° Y-axis + 90° Z-axis, with_negation=False)
only str_mp 8 exists, mapping onto voxel 22
    map_paint(parent_8 --> child_22, sym=180° Z-axis, with_negation=False)
only str_mp 5 exists, mapping onto voxel 23
    map_paint(parent_5 --> child_23, sym=180° Y-axis + 90° Z-axis, with_negation=False)
checking partner 25
checking partner 26
checking partner 21
checking partner 18
checking partner 15
checking partner 33
33 has sym and mesotype None
both str_mp 1 and comp_mp 28 exist, mapping 1 onto voxel 24
    map_paint(parent_1 --> child_24, sym=180° Y-axis + 90° Z-axis, with_negation=False)
only str_mp 5 exists, mapping onto voxel 25
    map_paint(parent_5 --> child_25, sym=180° Z-axis, with_negation=False)
only str_mp 4 exists, mapping onto voxel 26
    map_paint(parent_4 --> child_26, sym=180° Z-axis, with_negation=False)
skipping 27, already in mesovoxel
skipping 28, already in mesovoxel
skipping 29, already in mesovoxel
checking partner 31
checking partner 32
checking partner 27
checking partner 33
checking partner 21
21 has sym and mesotype structural
found partner voxel21 with type structural - setting map_variant to 29
both str_mp 2 and comp_mp 29 exist, mapping 29 onto voxel 30
    map_paint(parent_29 --> child_30, sym=180° Y-axis + 90° Z-axis, with_negation=False)
only str_mp 5 exists, mapping onto voxel 31
    map_paint(parent_5 --> child_31, sym=90° Z-axis, with_negation=False)
only str_mp 8 exists, mapping onto voxel 32
    map_paint(parent_8 --> child_32, sym=180° X-axis, with_negation=False)
checking partner 34
checking partner 35
checking partner 30
checking partner 27
checking partner 24
24 has sym and mesotype structural
found partner voxel24 with type structural - setting map_variant to 28
both str_mp 1 and comp_mp 28 exist, mapping 28 onto voxel 33
    map_paint(parent_28 --> child_33, sym=180° Y-axis + 90° Z-axis, with_negation=False)
only str_mp 4 exists, mapping onto voxel 34
    map_paint(parent_4 --> child_34, sym=180° X-axis, with_negation=False)
only str_mp 5 exists, mapping onto voxel 35
    map_paint(parent_5 --> child_35, sym=180° X-axis, with_negation=False)

In [50]:
painter2.mesovoxel.complementary_voxels

set()

In [34]:
df2 = lattice2.symmetry_df.symmetry_df
df2

,translation,90° X-axis,180° X-axis,270° X-axis,90° Y-axis,180° Y-axis,270° Y-axis,90° Z-axis,180° Z-axis,270° Z-axis,...,270° Z-axis + 180° X-axis,270° Z-axis + 180° Y-axis,270° Z-axis + 90° X-axis,270° Z-axis + 90° Y-axis,90° Y-axis + 180° Z-axis,90° Y-axis + 90° X-axis,90° Z-axis + 180° X-axis,90° Z-axis + 180° Y-axis,90° Z-axis + 90° X-axis,90° Z-axis + 90° Y-axis
"(4, 25)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(2, 8)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(7, 31)",False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(13, 34)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(15, 30)",False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"(14, 26)",False,False,True,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
"(9, 33)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(11, 20)",False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(27, 34)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(5, 28)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [35]:
# original sym_df
df1 = lattice.symmetry_df.symmetry_df
df1

,translation,90° X-axis,180° X-axis,270° X-axis,90° Y-axis,180° Y-axis,270° Y-axis,90° Z-axis,180° Z-axis,270° Z-axis,...,270° Z-axis + 180° X-axis,270° Z-axis + 180° Y-axis,270° Z-axis + 90° X-axis,270° Z-axis + 90° Y-axis,90° Y-axis + 180° Z-axis,90° Y-axis + 90° X-axis,90° Z-axis + 180° X-axis,90° Z-axis + 180° Y-axis,90° Z-axis + 90° X-axis,90° Z-axis + 90° Y-axis
"(4, 25)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(2, 8)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(7, 31)",False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(13, 34)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(15, 30)",False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"(14, 26)",False,False,True,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
"(9, 33)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(11, 20)",False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(27, 34)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
"(5, 28)",False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False